apiVersion: v1
kind: Service
metadata:
  name: oracle
spec:
  ports:
  - port: 1521
    protocol: TCP
    targetPort: 1521
  selector:
    app.kubernetes.io/name: oracle
  sessionAffinity: None
  type: ClusterIP